/*FILIPPO ROTOLO*/
CREATE DATABASE ESERCIZIO_DB;
USE ESERCIZIO_DB;

CREATE TABLE utente (
ID_U INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
Nome VARCHAR(255) NOT NULL,
Cognome VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL
);


CREATE TABLE categoria (
ID_CA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
Nome_Categoria ENUM('FrontEnd', 'BackEnd', 'FullStack', 'Cybersecurity')
);

CREATE TABLE corso (
ID_C INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
Nome_Corso VARCHAR(255) NOT NULL,
Descrizione_breve VARCHAR(255) NOT NULL,
Descrizione_completa TEXT NOT NULL,
Durata INT NOT NULL,
ID_CA INT NOT NULL,
FOREIGN KEY (ID_CA) REFERENCES categoria(ID_CA)
);


CREATE TABLE ruolo (
ID_R INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
TIPOLOGIA ENUM('Admin', 'Utente', 'Docente')
);

CREATE TABLE utenti_corsi(
ID_U INT NOT NULL,
ID_C INT NOT NULL,
PRIMARY KEY (ID_U,ID_C),
FOREIGN KEY (ID_U) REFERENCES utente(ID_U),
FOREIGN KEY (ID_C) REFERENCES corso(ID_C)
);

CREATE TABLE utente_ruolo(
ID_U INT NOT NULL,
ID_R INT NOT NULL,
PRIMARY KEY (ID_U,ID_R),
FOREIGN KEY (ID_U) REFERENCES utente(ID_U),
FOREIGN KEY (ID_R) REFERENCES ruolo(ID_R)
);

